name: 94486a7f-e046-461f-bbb9-334ec7b57040
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter
  - xarray=2022.3.0
  - intake
  - intake-xarray
  - rasterio==1.2.*
  - opencv
  - pytorch==1.8.0
  - torchvision==0.9.0
  - tqdm
  - hvplot
  - cartopy
  - datashader
  - jinja2==3.0.2
  - pycurl
  - geopandas
  - rioxarray
  - fiona
  - shapely
  - geoviews
  - pooch
  - pip
  - numpy==1.23.0
  - pip:
      - git+https://github.com/facebookresearch/detectron2.git